aws/pg_tle

- test/expected/pg_tle_management.out
- test/sql/pg_tle_management.sql
pg_tle does not allow installing trusted extensions. Installing the extension test_superuser_only_when_untrusted exercises the same functionality as installing the preceding extension test123, so removing that test extension.
> Regression test cleanup : remove redundant test extension

- tools/pg_tle_manage_local_extension/README.md
- tools/pg_tle_manage_local_extension/pg_tle_manage_local_extension.sh
1. Change short option for --sqldir from -s to -d
2. Fix where multiple SQL new install sql files are present
3. -d --debug will print some debug info
4. Now this script can be executed on MACOS
> Change short option for sqldir, add MAC OS support

- src/tleextension.c
- test/expected/pg_tle_management.out
- test/sql/pg_tle_management.sql
#154 
* Record a dependency of .sql and .control functions on pg_tle extension when installing a TLE.
* Block CREATE OR REPLACE only on pre-existing tle-installed .sql and .control functions, but allow for new tle-installed .sql and .control functions.
- If an unauthorized user tries to replace functions after they've been installed, or install new functions with the same 
names, they will still fail as before
- Function creation for new installs are still prevented by unauthorized users because of the default permissions on the 
pgtle schema as granted by
```
REVOKE ALL ON SCHEMA pgtle FROM PUBLIC;
GRANT USAGE ON SCHEMA pgtle TO PUBLIC;
```
Tested manually with
```
CREATE EXTENSION pg_tle;
SELECT pgtle.install_extension
(
'test123',
'1.1', …
```
> Fixes pg_restore for TLE-installed extensions

- docs/03_managing_extensions.md
Getting pg_dump and pg_restore to work for tle-installed extensions led to a change in the permissions model of schema pgtle. Capture this in documentation.
> Doc for permissions model of schema pgtle

- test/t/002_pg_tle_dump_restore.pl
Closes issue #152 
A first TAP test for dump and restore of a pg_tle installed extension. This is to put in place a basic sanity check to ensure that the logic for pg_dump and pg_restore work for pg_tle installed extensions. More extensive test cases will come later.
> TAP test that dumps a db with TLE and then restores to a new db

- Makefile
- docs/01_install.md
This adds the ability to specify the location of the `pg_config` binary through the `PG_CONFIG` variable in the Makefile, which helps for systems where `pg_config` is not in the path.
fixes #159
> Allow `PG_CONFIG` to be specified in Makefile

- .github/workflows/test-pg13.yaml
- include/compatibility.h
- src/guc-file.l
This fixes a noticed break when building against PostgreSQL 13, and adds a automated workflow to test `pg_tle` for PostgreSQL 13.
> Build fixes for PG13 + CI support

- .github/workflows/build_and_test.yml
- include/compatibility.h
- src/passcheck.c
- src/tleextension.c
This adds in a compatibility macro for "PG_CATCH" on versions of PostgreSQL older than 13 (where PG_FINALLY was introduced). We likely did not have any code that used PG_CATCH when the shim was introduced.
This also adds CI for building and testing PG12.
> Fix build issues on PG12 + add CI support

- docs/01_install.md
This specifies the current minimum version of PostgreSQL for `pg_tle`,
which happens to be PostgreSQL 11.
fixes #175
> Provide a minimum version of PostgreSQL for pg_tle

- tools/pg_tle_manage_local_extension/README.md
I tried following the docs and immediately ran into an error `Long arguments are not supported on MACOS`
This change is a suggestion to add better MacOS support. If you agree with the approach, I can do the same for the other commands.
> Docs: supporting MacOS

- .gitignore
- src/tleextension.c
- test/expected/pg_tle_perms_1.out
https://github.com/postgres/postgres/commit/e20b1ea1575cb523821d51e9934d8d6dab835335 added
"get_extension_schema()" to be an external function, so we no longer
need to define it for newer PostgreSQL versions.
> Fixes for PostgreSQL 16 builds

- src/tleextension.c
An issue with how file-based extension version files were copied while building the dependency graph caused bogus names to be available, and would prevent the proper requires tree from working if there were both TLE / file-based extensions in the dependency tree. This ensures the copy is handled in a way that does not send garbage.
fixes #183
> Fix "requires" for file-based extensions

- Makefile
- docs/03_managing_extensions.md
- pg_tle--1.0.1--1.0.4.sql
- src/tleextension.c
- test/expected/pg_tle_management.out
- test/sql/pg_tle_management.sql
Issue #186
Support for full install sql files of multiple versions of an extension, and corresponding uninstall functionality
1. Added the following function
**pgtle.install_extension_version_sql(name text, version text, ext text)**
which installs only the sql file of an extension version when another version of the extension is already installed, i.e., a control file and sql file for another version is already installed. No changes are made to the already installed control file.
2. Updated the following function
**pgtle.uninstall_extension(extname text, version text)**
which will now behave as follows
If extension + version does not exist -> error
If extension + version exists and is not the default_version -> uninstall extension/version combination
If extension + …
> Support full install and uninstall of multiple versions of an extension

- src/tleextension.c
Issue #195
Move return statements out of PG_TRY blocks in tleextension.c
> Remove return statements inside PG_TRY() blocks

- Makefile
- src/tleextension.c
- test/expected/pg_tle_management.out
- test/expected/pg_tle_versions.out
- test/sql/pg_tle_management.sql
- test/sql/pg_tle_versions.sql
- test/t/002_pg_tle_dump_restore.pl
An issue with how pg_tle records dependencies on the control and sql functions prevented TLEs from updating automatically via upgrade scripts to the desired version when created. This commit adds dependencies on the "base" TLE version and each necessary upgrade script.
pg_tle also did not support installing multiple versions of an extension, which has been corrected by adding "OR REPLACE" back to the control-string function (but not the sql-string function). The sql-string is executed first to detect duplicate versions being installed.
fixes #181
> Fix bug preventing TLEs auto-updating on install

- src/tleextension.c
- test/expected/pg_tle_management.out
- test/sql/pg_tle_management.sql
Fix issue #208 
The root cause of the crash is when the transaction fails, it's set to aborted state; get_extension_oid function needs a relcache lookup which must be done in a transaction state.
This change fixes this issue by skipping TransactionStmts in process utility hook.
> Fix a bug that rollback a failed transaction causes server crash.

- src/tleextension.c
- test/expected/pg_tle_versions.out
- test/sql/pg_tle_versions.sql
When recording TLE dependencies for pg_dump/restore, read the extension control file whether an explicit version is specified or not.
fixes #181
> Fix segfault when creating explicit TLE version

- include/constants.h
- pg_tle--1.0.4--1.0.5.sql
- pg_tle--1.0.5.sql
- src/datatype.c
- test/expected/pg_tle_datatype.out
- test/sql/pg_tle_datatype.sql
pgtle_admin can run `create_operator_func` to create operator funcs for base types created in pg_tle (by `create_base_type`).
User-defined operator function must accept one or two arguments of BYTEA, we make an C-version operator function that accepts base type as the argument; inside the C-version operator function, we find the user-defined operator function and execute it.
Notes:
1. `create_operator_func` is not strictly necessary to define an operator function on the base type; however, it will be required for languages such as plrust, because the custom base type is not available in plrust;
2. `CREATE OPERATOR CLASS` requires superuser privileges in pg_tle, but should be already supported in AWS RDS.
By submitting this pull request, I confirm that my contribution is made under the …
> Implement create_operator_func API.

- test/t/002_pg_tle_dump_restore.pl
Update the post-`pg_restore` checks to point to the restored database instead of the original database.
> Fix typo in `pg_dump`/`pg_restore` TAP test

- include/compatibility.h
- src/datatype.c
- test/expected/pg_tle_datatype.out
- test/sql/pg_tle_datatype.sql
Every custom data type is stored as bytea, so the conversion to bytea is always valid. But bytea to custom data type may not be always valid.
This can help users to process the new data type, as they can utilize helper functions defined on bytea.
Defined a function `CastCreate` in compatibility.h for version < 130000 because it is only introduced after pg13.
> Create explicit cast from custom data type to bytea.

- .github/workflows/build_and_test.yml
PostgreSQL branched for v16, so we need to test this explicit branch for v16 compatibility.
Also note that v16 introduced the meson build system, so at some point we'll need to add support for that vis-a-vis the CI/CD.
> Add REL_16_STABLE to CI/CD

- include/constants.h
- src/datatype.c
- test/expected/pg_tle_datatype.out
- test/sql/pg_tle_datatype.sql
Although this is not strictly required in `CREATE TYPE` command, it's generally preferred. If there's a strong reason to lift the restriction in the future, we can re-consider at that time.
Also, refactored `check_user_defined_func` and `find_user_defined_func ` function a bit to improve readability.
Reference:
https://github.com/postgres/postgres/blob/master/src/backend/commands/typecmds.c#L1987
https://www.postgresql.org/docs/current/sql-createtype.html
> Require type I/O function to be immutable and strict.

- include/compatibility.h
- src/tleextension.c
- test/expected/pg_tle_datatype.out
- test/sql/pg_tle_datatype.sql
If a user-defined function is used by pgtle datatype API (i.e. `create_base_type` or `create_operator_func`), we will define a C-version function with the same name (different argument types).
Replacing or altering these functions can be error-prone. For example, if a user defined function is renamed, we won't be able to find it in the C version function because we rely on the same name as a mapping.
One note is that for operator functions, it will only be restricted if it's created or used by `create_operator_func` API.
Dropping these functions is still allowed, and will drop the dependent objects cascade.
Blocked commands:
1. `CREATE OR REPLACE FUNCTION xxx`;
2. `ALTER FUNCTION xxx`;
3. `ALTER FUNCTION xxx RENAME TO xxx`;
4. `ALTER FUNCTION xxx SET SCHEMA xxx`;
5. `ALTER FUNCTION xxx …
> Disallow REPLACE or ALTER functions used or defined by pg_tle datatype APIs.

- docs/00_intro.md
- docs/03_managing_extensions.md
- docs/06_plpgsql_examples.md
- docs/09_datatypes.md
Add data type API doc and examples
> Add base datatype API doc and examples.

- src/tleextension.c
`ALTER FUNCTION OWNER` is executed on pg_tle type functions during pg_upgrade; without this change, pg_upgrade with pg_tle type would fail.
> Allow `ALTER FUNCTION OWNER` during upgrade.

- docs/04_hooks.md
- examples/client_lockout.sql
Documentation on clientauth hook (PR #227). The format is based on the documentation for the passcheck hook. An example SQL file containing a clientauth extension is added under the `examples` directory.
> Add clientauth documentation and example

- src/tleextension.c
- test/t/002_pg_tle_dump_restore.pl
Issue #, if available: #228
Add dependencies on control and sql functions when an extension is created via cascade. Previously these dependencies were recorded only for the top-level extension. This PR moves this logic to CreateExtensionInternal where it is run for each cascading TLE.
Running the scenario reported in #228:
```
postgres=# create extension pg_tle;
CREATE EXTENSION
postgres=# select pgtle.install_extension(
postgres(#     'ofoo',
postgres(#     '1',
postgres(#     'ofoo',
postgres(#     'create function ofoo_exists() returns int language sql as $$select 1$$'
postgres(# );
install_extension
-------------------
t
(1 row)
postgres=# select pgtle.install_extension(
postgres(#     'obar',
postgres(#     '1',
postgres(#     'obar',
postgres(#     'create …
```
> Add missing dependencies on control/SQL functions when TLE is created via cascade

- src/passcheck.c
- test/expected/pg_tle_api.out
- test/sql/pg_tle_api.sql
Issue #, if available: #230
Description of changes: Use TimestampTzGetDatum to convert the validuntil_time to a Datum with the correct value.
This fix was originally in #232 but I am splitting it into its own PR so that it doesn't get held up by the other changes in that PR.
> Fix validuntil time in passcheck

- test/expected/pg_tle_api.out
- test/expected/pg_tle_api_clusterwide.out
- test/sql/pg_tle_api.sql
- test/sql/pg_tle_api_clusterwide.sql
Description of changes: New validuntil test in pg_tle_api.sql is failing occasionally due to timing issue after pg_reload_conf. Reconnect to database using \c after each pg_reload_conf to ensure parameters are updated.
> Fix flaky test failure from pg_reload_conf timing

- docs/04_hooks.md
Issue #, if available: #229
Update docs with the new parameter `pgtle.passcheck_db_name` and cluster-wide passcheck mode.
> Update docs for cluster-wide passcheck

- src/tleextension.c
- test/expected/pg_tle_management.out
- test/sql/pg_tle_management.sql
Issue #, if available: #241
Description of changes: Add `@` to the extension name character whitelist
> Allow `@` character in extension names

- src/tleextension.c
- test/t/002_pg_tle_dump_restore.pl
Issue #, if available: https://github.com/aws/pg_tle/issues/249
Description of changes: Allow superuser to ALTER OWNER of datatype functions. Needed to unblock pg_dump/pg_restore of custom datatypes. pg_restore won't succeed for non-superuser roles regardless since create extension pg_tle requires superuser.
A fix for 002_pg_tle_dump_restore.pl is included. With the updated test, the original code fails as expected.
> Allow superuser to ALTER OWNER of datatype functions

- src/tleextension.c
- test/t/002_pg_tle_dump_restore.pl
Issue #245
Records dependencies of default version sql functions on the TLE. This fixes failures during pg_dump/pg_restore due to `<extensionName>--<defaultVersion>.sql` function being created after the extension in `pg_dump` (see #245 for details).
> Record dependency of default version sql func on the extension

- src/clientauth.c
- test/t/004_pg_tle_clientauth.pl
Issue #, if available: https://github.com/aws/pg_tle/issues/252
Description of changes: On init, check if clientauth's workers have been added to the registration list. If any are missing then fail postmaster startup. Emit an error for administrator to check `max_worker_processes` and `pgtle.clientauth_num_parallel_workers`.
> Block postmaster startup if clientauth background workers fail to register

- src/clientauth.c
- src/passcheck.c
Description of changes: After each clientauth and passcheck request is completed by the background worker, erase the shared memory entry to prevent sensitive information from persisting longer than necessary.
> Erase shared memory entry after each clientauth/passcheck request

- src/clientauth.c
- test/t/004_pg_tle_clientauth.pl
Description of changes: Use quote_identifier to prevent SQL injections and support identifiers containing double quote characters.
> Quote clientauth identifiers

- examples/ndistinct/README.md
- examples/ndistinct/ndistinct.sql
Description of changes: Add an example of a pl/rust function that calculates and sets the n_distinct value of a column.
The calculation is performed using the HLL [1] extension.
[1] https://github.com/citusdata/postgresql-hll
> Add example of ndistinct computation

- src/passcheck.c
- test/t/005_pg_tle_passcheck_clusterwide.pl
Needed so that passcheck can accurately check whether the worker has been registered (https://github.com/aws/pg_tle/blob/main/src/passcheck.c#L306)
> Init passcheck worker_handle to NULL

- docs/04_hooks.md
Update the SQL command to set enable_clientauth hook in the 2nd example in the hook doc.
It has a typo suggesting to activate enable_password_check hook instead.
> Refactor typo in 04_hooks.md doc

- docs/03_managing_extensions.md
Issue #, if available: None
Description of changes: 
Updated [03_managing_extensions.md](https://github.com/aws/pg_tle/blob/main/docs/03_managing_extensions.md) to reflect the correct column names for `pgtle.available_extensions()` and `pgtle.available_extension_versions()`.
As shown below, the column name is `comment`:
```
test=# SELECT * FROM pgtle.available_extensions();
name     | default_version |              comment              
-------------+-----------------+-----------------------------------```
```
and
```
test=# SELECT * FROM pgtle.available_extension_versions();
name     | version | superuser | trusted | relocatable | schema | requires |              comment              
-------------+---------+-----------+---------+-------------+--------+----------+------------------------- …
> Update column name for pgtle functions

- .github/workflows/code_coverage.yml
- .github/workflows/test.yml
Description of changes: Our GH Actions are running on Node 16 which is being deprecated by GitHub. Update `checkout` and `upload-artifacts` from v3 to v4 which run on Node 20.
I tested this in my fork and verified that the behaviour is the same.
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> Update checkout to v4 and upload-artifacts to v4

- .github/workflows/code_coverage.yml
- .github/workflows/test.yml
- include/compatibility.h
- src/clientauth.c
Description of changes: [b43100f](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=b43100f) changes BackgroundWorkerList from slist to dlist. Add compatibility macro for this.
Add REL_17_STABLE to the CI.
> Fix build failure on Postgres master

- include/compatibility.h
- src/tleextension.c
**Issue #, if available:**
Postgres master branch commit [3eea7a0](https://github.com/postgres/postgres/commit/3eea7a0c97e94f9570af87317ce3f6a41eb62768) simplified the executor's parallel mode determination by:
Removing the execute_once parameter from ExecutorRun
Relying on QueryDesc.already_executed flag instead
Moving the logic to ExecutePlan
This API change in PostgreSQL master broke pg_tle's CI build because pg_tle was using the 4-parameter version of ExecutorRun.
**Description of changes:**
Added version-specific compatibility macro EXECUTOR_RUN that:
For PostgreSQL 18+ (master): Uses the new 3-parameter version
`ExecutorRun(queryDesc, direction, count)`
For PostgreSQL 17 and earlier: Uses the existing 4-parameter version with true
`ExecutorRun(queryDesc, direction, count, true)`
By …
> Fix master branch ExecutorRunParams change CI failure

- .github/workflows/code_coverage.yml
- .github/workflows/test.yml
Description of changes: The new Ubuntu 24.04 image removed readline by default which broke Postgres compilation.
https://github.com/actions/runner-images/issues/10636
> Install libreadline-dev in CI workflow

- Makefile
- pg_tle--1.4.1--1.5.0.sql
- src/tleextension.c
- test/expected/pg_tle_api_clusterwide.out
- test/expected/pg_tle_extension_schema.out
- test/expected/pg_tle_functions_acl.out
- test/sql/pg_tle_api_clusterwide.sql
- test/sql/pg_tle_extension_schema.sql
- test/sql/pg_tle_functions_acl.sql
- test/t/002_pg_tle_dump_restore.pl
Issue #284:
Added optional _schema_ parameter to install_extension function and implemented adding _schema_ configuration to generated control file.
Updated current extension version to 1.5.0 as the change is not forward compatible. 
> Added schema parameter to install_extension

- docs/03_managing_extensions.md
- pg_tle--1.4.1--1.5.0.sql
- src/tleextension.c
- test/expected/pg_tle_extension_schema.out
- test/expected/pg_tle_functions_acl.out
- test/expected/pg_tle_management.out
- test/sql/pg_tle_extension_schema.sql
- test/t/002_pg_tle_dump_restore.pl
Description of changes: `pgtle.available_extension_versions()` returns more fields than `pgtle.available_extensions()` including the schema field which can now be modified. It doesn't really make sense for the two functions to return different signatures, so add those missing fields to `pgtle.available_extensions()`.
This changes the output returned by `SELECT * FROM pgtle.available_extensions()` so callers should be aware of that. However, the output is identical if the three columns from before are specified, i.e `SELECT name, default_version, comment FROM pgtle.available_extensions()`. This change is part of the 1.5.0 minor version bump.
Add the updated functions to the documentation.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
> Change return signature of `pgtle.available_extensions()` to match `pgtle.available_extension_versions()`.

- docs/03_managing_extensions.md
Issue #, if available: #281
Description of changes: Fix example of `pgtle.install_extension_version_sql` in `03_managing_extensions.md`.
> Fix pgtle.install_extension_version_sql example

- src/tleextension.c
Description of changes: Fix CI build on Postgres master branch. The signature of CreateQueryDesc is updated in [525392d5727](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=525392d5727).
The new parameter lets you provide a CachedPlan. Prior to this commit, the CachedPlan is NULL by default. To preserve the previous behaviour we can just pass NULL.
> Update CreateQueryDesc signature on PG18.

- docs/04_hooks.md
- include/constants.h
- pg_tle--1.4.1--1.5.0.sql
- src/clientauth.c
- test/t/004_pg_tle_clientauth.pl
#290 
Adding additional column application_name to the clientauth_port_subset.
> Additional parameter application_name to clientauth_port_subset (clientauth)
